name: genx3d
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - langchain
  - langgraph
  - langchain-openai
  # - cadquery=2.3.0
  - pydantic
  - jinja2
  - python-dotenv
  - starlette
  - gunicorn
  - pip
  - pip:
    - langchain_community